### ISSUE TITLE
undefined method `user' for LWRP resource vagrant_plugin from cookbook vagrant

### ISSUE THREAD

**Issue by mrdimka** [jtimberman/vagrant-cookbook#30]
I am trying to install some plugins with the following recipe.

```
include_recipe 'vagrant'

%w(vagrant-omnibus vagrant-berkshelf).each do |vagrant_plugin|
  vagrant_plugin vagrant_plugin do
  	user 'myuser'
  end
end
```

but it fails with the following output
```
chef-client fails Recipe Compile Error in /var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb
================================================================================

NoMethodError
-------------
undefined method `user' for LWRP resource vagrant_plugin from cookbook vagrant

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb:14:in `block (2 levels) in from_file'
  /var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb:13:in `block in from_file'
  /var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb:12:in `each'
  /var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb:12:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/mycookbook/recipes/my-vagrant.rb:

  7:  # All rights reserved - Do Not Redistribute
  8:  #
  9:  
 10:  include_recipe 'vagrant'
 11:  
 12:  %w(vagrant-omnibus vagrant-berkshelf).each do |vagrant_plugin|
 13:    vagrant_plugin vagrant_plugin do
 14>>   	user 'myuser'
 15:    end
 16:  end 17:  


Running handlers:
[2015-07-16T06:36:37-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-16T06:36:37-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 7.279798544 seconds
[2015-07-16T06:36:37-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-07-16T06:36:37-04:00] ERROR: undefined method `user' for LWRP resource vagrant_plugin from cookbook vagrant
[2015-07-16T06:36:37-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
vagrant version used is 1.7.3

**Comment by jtimberman** [comment]
Please try again with version 0.3.0 (just released to supermarket).

**Comment by mrdimka** [comment]
Just tested with version 0.3.0 and I confirm that is fixed.
Thank you.
