### ISSUE TITLE
'vagrant_plugin[vagrant-aws]' Bundler ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by andreimahu** [jtimberman/vagrant-cookbook#78]
I am installing a total of 4 vagrant plugins but only the aws one fails. Installing it with "vagrant plugin install aws" works fine.

Here is the error:

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of vagrant plugin install vagrant-aws ----
    STDOUT: Installing the 'vagrant-aws' plugin. This can take a few minutes...
    Building native extensions.  This could take a while...
    STDERR: Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    ERROR: Failed to build gem native extension.

        current directory: /root/.vagrant.d/gems/2.4.2/gems/nokogiri-1.8.1/ext/nokogiri
    /opt/vagrant/embedded/bin/ruby -r ./siteconf20171219-4367-17p0qz8.rb extconf.rb
    checking if the C compiler accepts ... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --help
        --clean
    /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:407:in `<main>'

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

      /root/.vagrant.d/gems/2.4.2/extensions/x86_64-linux/2.4.0/nokogiri-1.8.1/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in /root/.vagrant.d/gems/2.4.2/gems/nokogiri-1.8.1 for inspection.
    Results logged to /root/.vagrant.d/gems/2.4.2/extensions/x86_64-linux/2.4.0/nokogiri-1.8.1/gem_make.out
    ---- End output of vagrant plugin install vagrant-aws ----
    Ran vagrant plugin install vagrant-aws returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/vagrant/libraries/plugin.rb:73:in `execute_cli'
    /var/chef/cache/cookbooks/vagrant/libraries/plugin.rb:46:in `install'
    /var/chef/cache/cookbooks/vagrant/providers/plugin.rb:40:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/vagrant/providers/plugin.rb:39:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/vagrant/recipes/install_plugins.rb

     26:     vagrant_plugin plugin do
     27:       user node['vagrant']['user'] if node['vagrant']['user']
     28:       password node['vagrant']['password'] if node['vagrant']['password']
     29:     end
     30:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/vagrant/recipes/install_plugins.rb:26:in `block in from_file'

    vagrant_plugin("vagrant-aws") do
      action [:install]
      default_guard_interpreter :default
      declared_type :vagrant_plugin
      cookbook_name "vagrant"
      recipe_name "install_plugins"
    end

    System Info:
    ------------
    chef_version=13.6.4
    platform=amazon
    platform_version=2017.09
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-client worker: ppid=3785;start=10:41:57;
    executable=/opt/chef/bin/chef-client

**Comment by andreimahu** [comment]
Found the issue... 1 minute after rushing out the issue. The plugin is called "aws" and not "vagrant-aws".
